return {}
-- return {
-- 	"nvimdev/dashboard-nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		local logo = [[
-- ⠀⠀⠀⠀⠀⠀⠀⣠⡤⠶⡄⠀⠀⠀⠀⠀⠀⠀⢠⠶⣦⣀⠀⠀⠀⠀⠀⠀⠀
-- ⠀⠀⠀⠀⢀⣴⣿⡟⠀⠈⣀⣾⣝⣯⣿⣛⣷⣦⡀⠀⠈⢿⣿⣦⡀⠀⠀⠀⠀
-- ⠀⠀⠀⣴⣿⣿⣿⡇⠀⢼⣿⣽⣿⢻⣿⣻⣿⣟⣷⡄⠀⢸⣿⣿⣾⣄⠀⠀⠀
-- ⠀⠀⣞⣿⣿⣿⣿⣷⣤⣸⣟⣿⣿⣻⣯⣿⣿⣿⣿⣀⣴⣿⣿⣿⣿⣯⣆⠀⠀
-- ⠀⡼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣜⡆⠀
-- ⢠⣟⣯⣿⣿⣿⣷⢿⣫⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣬⣟⠿⣿⣿⣿⣿⡷⣾⠀
-- ⢸⣯⣿⣿⡏⠙⡇⣾⣟⣿⡿⢿⣿⣿⣿⣿⣿⢿⣟⡿⣿⠀⡟⠉⢹⣿⣿⢿⡄
-- ⢸⣯⡿⢿⠀⠀⠱⢈⣿⢿⣿⡿⣏⣿⣿⣿⣿⣿⣿⣿⣿⣀⠃⠀⢸⡿⣿⣿⡇
-- ⢸⣿⣇⠈⢃⣴⠟⠛⢉⣸⣇⣹⣿⣿⠚⡿⣿⣉⣿⠃⠈⠙⢻⡄⠎⠀⣿⡷⠃
-- ⠈⡇⣿⠀⠀⠻⣤⠠⣿⠉⢻⡟⢷⣝⣷⠉⣿⢿⡻⣃⢀⢤⢀⡏⠀⢠⡏⡼⠀
-- ⠀⠘⠘⡅⠀⣔⠚⢀⣉⣻⡾⢡⡾⣻⣧⡾⢃⣈⣳⢧⡘⠤⠞⠁⠀⡼⠁⠀⠀
-- ⠀⠀⠀⠸⡀⠀⢠⡎⣝⠉⢰⠾⠿⢯⡘⢧⡧⠄⠀⡄⢻⠀⠀⠀⢰⠁⠀⠀⠀
-- ⠀⠀⠀⠀⠁⠀⠈⢧⣈⠀⠘⢦⠀⣀⠇⣼⠃⠰⣄⣡⠞⠀⠀⠀⠀⠀⠀⠀⠀
-- ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⢤⠼⠁⠀⠀⠳⣤⡼⠀⠀⠀⠀⠀⠀
--     ]]
-- 		logo = string.rep("\n", 2) .. logo
-- 		require("dashboard").setup({
-- 			theme = "doom",
-- 			config = {
-- 				header = vim.split(logo, "\n"),
-- 				center = {
-- 					{
-- 						icon = " ",
-- 						icon_hl = "Title",
-- 						desc = "Find File",
-- 						desc_hl = "String",
-- 						key = "b",
-- 						keymap = "<C-p>",
-- 						key_hl = "Number",
-- 						key_format = " %s", -- remove default surrounding `[]`
-- 						action = "Telescope find_files",
-- 					},
-- 					{
-- 						icon = " ",
-- 						icon_hl = "Title",
-- 						desc = "Find File",
-- 						desc_hl = "String",
-- 						key = "f",
-- 						keymap = "<C-p>",
-- 						key_hl = "Number",
-- 						key_format = " %s", -- remove default surrounding `[]`
-- 						action = "Telescope find_files",
-- 					},
-- 				},
-- 				footer = {}, --your footer
-- 			},
-- 		})
-- 	end,
-- 	dependencies = { { "nvim-tree/nvim-web-devicons" } },
-- }
