-- vim.cmd.colorscheme("rose-pine-moon")
-- vim.cmd.colorscheme("gruvbox")
-- vim.cmd.colorscheme("catppuccin-mocha")
-- vim.cmd.colorscheme("catppuccin-frappe")
-- vim.cmd.colorscheme("tokyonight-moon")
-- vim.cmd.colorscheme("onedark")
vim.cmd.colorscheme("poimandres")
-- vim.cmd.colorscheme("tokyonight-night")
-- vim.cmd.colorscheme("neopywal")
-- vim.cmd.colorscheme("cyberdream")

-- vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
-- vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
