import os
import re
from pathlib import Path
from urllib.parse import urljoin

ROOT_PATH = Path(__file__).resolve().parents[1]


def github_url(plugin: str):
    return urljoin("https://github.com", plugin)


plugins = set()
colorschemes = set()

GITHUB_URL_REGEX = r"[\"']([a-zA-Z0-9-.]+\/[a-zA-Z0-9-.]+)[\"']"

for root, dirs, files in os.walk(ROOT_PATH / "lua/plugins"):
    for file in files:
        absolute_path = Path(root) / file

        group = colorschemes if "colorscheme" in root else plugins

        with open(absolute_path, "r") as f:
            file_contents = f.read()
            parsed_plugins = re.findall(GITHUB_URL_REGEX, file_contents)
            for plugin in parsed_plugins:
                group.add(plugin)

plugins = sorted(plugins)
colorschemes = sorted(colorschemes)

with open(ROOT_PATH / "README.md", "w+") as out_file:
    with open(ROOT_PATH / "scripts/readme-base.md", "r") as readme_base:
        out_file.write(readme_base.readline())

    out_file.write("\n## Plugins\n\n")
    for plugin in plugins:
        out_file.write(f"- [{plugin}]({github_url(plugin)})\n")

    out_file.write("\n## Colorschemes\n\n")
    for colorscheme in colorschemes:
        out_file.write(f"- [{colorscheme}]({github_url(colorscheme)})\n")

    out_file.write("\nREADME autogenerated by [readme-gen.py](readme-gen.py)")
