return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	opts = {
		auto_update = true,
		ensure_installed = {
			"clangd",
			"gopls",
			"jsonls",
			"lua-language-server",
			"markdown_oxide",
			"prettier",
			"pyright",
			"ruff",
			"rust-analyzer",
			"rustywind",
			"sql-formatter",
			"stylua",
			"svelte-language-server",
			"tailwindcss-language-server",
			"texlab",
			"tinymist",
			"typstyle",
			"yamlfmt",
		},
	},
}
